apiVersion: v1
kind: ConfigMap
metadata:
  name: app-web-config
  labels:
    app.kubernetes.io/name: app-web
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: app-web
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: appdb
  APP_USER: app-user
