apiVersion: v1
kind: Secret
metadata:
  name: app-web-secrets
  labels:
    app.kubernetes.io/name: app-web
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: app-web
type: Opaque
stringData:
  APP_PASSWORD: 01senha
