apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
        - name: app-web
          image: alissondrs/app-web:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "mysql-service.default.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: APP_USER
              value: "app-web2"
            - name: APP_PASSWORD
              value: "01senha"
            - name: DB_NAME
              value: "app_web"

---
apiVersion: v1
kind: Service
metadata:
  name: app-web-service
spec:
  selector:
    app: app-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
