apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
        - name: app-web
          image: alissondrs/app-web:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_NAME
              value: appdb
            - name: DB_HOST
              value: "mysql-service.kube-system.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: APP_USER
              value: app-user
            - name: APP_PASSWORD
              value: 02senha
          # command: ["flask", "run", "--host", "0.0.0.0", "--port", "8080"]
---
apiVersion: v1
kind: Service
metadata:
  name: app-web-service
spec:
  selector:
    app: app-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
