{
 "title": "app-web dash",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Saturação",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\r\n",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "MEM"
    }
   ]
  },
  {
   "title": "Health Check",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(app_health_check_total{status_code=\"200\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de sucesso",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_total{status=~\"2..\"}[1m])) / sum(rate(flask_http_request_total[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(app_health_check_histogram_bucket[5m]))"
    },
    {
     "expr": "histogram_quantile(0.95, rate(app_health_check_histogram_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de erros",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_total{status=~\"5..\"}[1m])) / sum(rate(flask_http_request_total[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}