apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app/configmap.yaml
  - app/secret.yaml
  - app/deployment.yaml
  - app/service.yaml
  - mysql/configmap-initdb.yaml
  - mysql/secret.yaml
  - mysql/service-headless.yaml
  - mysql/service.yaml
  - mysql/statefulset.yaml
