apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: app-web
data:
  init.sql: |
    USE appdb;
    CREATE TABLE IF NOT EXISTS usuarios (
      id INT AUTO_INCREMENT PRIMARY KEY,
      nome VARCHAR(255),
      idade INT
    );
    GRANT ALL PRIVILEGES ON appdb.* TO 'app-user'@'%';
    FLUSH PRIVILEGES;
