apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: app-web
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: 01senha
  MYSQL_PASSWORD: 01senha
